HelloJob.App/Areas/Admin/Controllers/VacancyController.cs
using HelloJob.Core.Helper.MailHelper;
using HelloJob.Core.Utilities.Results.Concrete.ErrorResults;
using HelloJob.Core.Utilities.Results.Concrete.SuccessResults;
using HelloJob.Entities.DTOS;
using HelloJob.Entities.Enums;
using HelloJob.Entities.Models;
using HelloJob.Service.Services.Implementations;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace HelloJob.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class VacancyController : Controller
    {
        readonly IVacancyService _VacancyService;
        readonly ICategoryService _categoryService;
        readonly ICityService _cityService;
        readonly ICompanyService _companyService;
        readonly IEmailHelper _emailHelper;
        public VacancyController(IVacancyService VacancyService, ICategoryService categoryService, IEmailHelper emailHelper, ICityService cityService, ICompanyService companyService)
        {
            _VacancyService = VacancyService;
            _categoryService = categoryService;
            _emailHelper = emailHelper;
            _cityService = cityService;
            _companyService = companyService;
        }

        public async Task<IActionResult> Index(string userid=null,int page = 1, int pagesize = 6)
        {
            return View(await _VacancyService.GetAllAsync(userid,true,page, pagesize));
        }

        public async Task<VacancyGetDto> GetVacancyById(int VacancyId)
        {
            var res = await _VacancyService.GetAsync(VacancyId);
            return res.Data ;
        }
        [HttpPost]
        public async Task<IActionResult> Accept(int id)
        {
            var result = await ProcessOrderStatus(id, "Muracietiniz qebul olundu");
            if (result.Success)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            else
            {
                return View(nameof(Index));
            }
        }
        [HttpPost]
        public async Task<IActionResult> Reject(int id)
        {
            var result = await ProcessOrderStatus(id, "Muracietiniz red edildi");

            if (result.Success)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            else
            {
                return View(nameof(Index));
            }
        }
        [HttpPost]
        public async Task<IActionResult> Pending(int id)
        {
            var result = await ProcessOrderStatus(id, "Muracietiniz gozlemededi");

            if (result.Success)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            else
            {
                return View(nameof(Index));
            }
        }
        private async Task<HelloJob.Core.Utilities.Results.Abstract.IResult> ProcessOrderStatus(int id, string emailSubject)
        {
            var Vacancy = await GetVacancyById(id);

            if (Vacancy == null)
            {
                return new ErrorResult("Vacancy tapilmadi");
            }

            var userEmail = Vacancy.Company.AppUser.Email;

            var orderStatus = GetOrderStatusFromEmailSubject(emailSubject);

            if (orderStatus == Order.None)
            {
                var result = await _VacancyService.SetOrderStatus(id, orderStatus);

                if (result.Success)
                {
                    var notificationResult = await _emailHelper.SendNotificationEmailAsync(userEmail, "Pending", "netice gozlenilir");

                    if (notificationResult.Success)
                    {
                        return new SuccessResult("Pending bildirimi gönderildi");
                    }
                    else
                    {
                        return new ErrorResult("Pending bildirimi gönderilmedi");
                    }
                }
                else
                {
                    return new ErrorResult(result.Message);
                }
            }
            else
            {
                var result = await _VacancyService.SetOrderStatus(id, orderStatus);

                if (result.Success)
                {
                    var notificationResult = await _emailHelper.SendNotificationEmailAsync(userEmail, emailSubject, emailSubject);

                    if (notificationResult.Success)
                    {
                        return new SuccessResult(result.Message);
                    }
                    else
                    {
                        return new ErrorResult("Melumatlandirici e-postası gönderilmedi");
                    }
                }
                else
                {
                    return new ErrorResult(result.Message);
                }
            }
        }

        private Order GetOrderStatusFromEmailSubject(string emailSubject)
        {
            if (emailSubject == "Muracietiniz qebul olundu")
            {
                return Order.Accept;
            }
            else if (emailSubject == "Muracietiniz red edildi")
            {
                return Order.Reject;
            }
            else
            {
                return Order.None;
            }
        }


    }
}

HelloJob.App/Areas/User/Controllers/VacancyController.cs
using HelloJob.Entities.DTOS;
using HelloJob.Entities.Models;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace HelloJob.App.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "Owner")]
    public class VacancyController : Controller
    {
        readonly IVacancyService _VacancyService;
        readonly ICategoryService _categoryService;
        readonly ICityService _cityService;
        readonly ICompanyService _companyService;
        public VacancyController(IVacancyService VacancyService, ICategoryService categoryService, ICityService cityService, ICompanyService companyService)
        {
            _VacancyService = VacancyService;
            _categoryService = categoryService;
            _cityService = cityService;
            _companyService = companyService;
        }

        public async Task<IActionResult> Index(string userid,int page = 1,int pagesize=6)
        {
             userid = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var res = await _VacancyService.GetAllAsync(userid, false, page, pagesize);
            return View(res.Datas);
        }

        [Authorize(Roles = "Owner")]

        public async Task<IActionResult> Create()
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.Companies = await  _companyService.GetAllAsync(userId,false,1,6);
            ViewBag.UserId = userId;
            ViewBag.Categories = await _categoryService.GetAllAsync();
            ViewBag.Cities = await _cityService.GetAllAsync();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner")]


        public async Task<IActionResult> Create(VacancyPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = await _categoryService.GetAllAsync();
                ViewBag.Cities = await _cityService.GetAllAsync();
                var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                ViewBag.Companies = await _companyService.GetAllAsync(userId, false, 1, 6);

                return View();
            }
            var response = await _VacancyService.CreateAsync(dto);
            CompanyGetDto company =(await _companyService.GetAsync(dto.CompanyId)).Data;

            if (!response.Success)
            {
                ViewBag.Categories = await _categoryService.GetAllAsync();
                ViewBag.Cities = await _cityService.GetAllAsync();
                var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                ViewBag.Companies = await _companyService.GetAllAsync(userId, false, 1, 6);

                ModelState.AddModelError("", response.Message);
                return View();
            }

            return RedirectToAction(nameof(Index), new { userid = company.AppUser.Id });
        }

        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Categories = await _categoryService.GetAllAsync();
            ViewBag.Cities = await _cityService.GetAllAsync();

            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.UserId = userId;
            ViewBag.Companies = await _companyService.GetAllAsync(userId, false, 1, 6);

            var res = await _VacancyService.GetAsync(id);
            return View(res.Data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner")]

        public async Task<IActionResult> Update(int id, VacancyPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = await _categoryService.GetAllAsync();
                ViewBag.Cities = await _cityService.GetAllAsync();
                var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
                ViewBag.Companies = await _companyService.GetAllAsync(userId, false, 1, 6);

                var res = await _VacancyService.GetAsync(id);
                return View(res.Data);
            }
            var response = await _VacancyService.UpdateAsync(id, dto);

            if (!response.Success)
            {
                ViewBag.Categories = await _categoryService.GetAllAsync();
                ViewBag.Cities = await _cityService.GetAllAsync();

                ModelState.AddModelError("", response.Message);
                var res = await _VacancyService.GetAsync(id);
                return View(res.Data);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Remove(int id)
        {
            var res = await _VacancyService.RemoveAsync(id);
            if (!res.Success)
            {
                ModelState.AddModelError("", res.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

HelloJob.App/Areas/User/Views/Vacancy/Create.cshtml
@model VacancyPostDto
<div class="create_vacans">
    <div class="title">
        <h1>Vakansiya Yerləşdir</h1>
        <ul class="profile__add-vacans__parts">
            <li class="active">
                <a href="#tab1" class=" step_btn">İş barədə məlumatlar</a>
            </li>
        </ul>
    </div>
    <div class="inner_tab">
        <form asp-action="Create" asp-controller="vacancy" enctype="multipart/form-data" method="post">
            <div class="row mb-5">
                <div class="col-lg-2">
                    <h2 class="section_title">İş barədə məlumatlar</h2>
                </div>
                <div class="col-lg-10">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <div class="cv_inputs">
                                    <label for="">Vezife</label>
                                    <input type="text"
                                           asp-for="Position"
                                           class="form-control inputs"
                                           placeholder="Positioninizi yazın" />
                                    <span class="text text-danger" asp-validation-for="Position"></span>

                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">Şirkət adı</label>
                                <select asp-for="CompanyId" id="" class="form-control cities">
                                    @foreach (var item in ViewBag.Companies.Datas)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }
                                </select>
                                <span class="text text-danger" asp-validation-for="CompanyId"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">Kateqoriya</label>
                                <select asp-for="CategoryId" class="form-control cities">
                                    @foreach (var category in ((IEnumerable<CategoryGetDto>)ViewBag.Categories.Datas).Where(c => c.ParentId == null))
                                    {
                                        <optgroup label="@category.Name">
                                            @foreach (var subCategory in ((IEnumerable<CategoryGetDto>)ViewBag.Categories.Datas).Where(c => c.ParentId == category.Id))
                                            {
                                                <option value="@subCategory.Id">@subCategory.Name</option>
                                            }
                                        </optgroup>
                                    }
                                </select>
                                <span class="text text-danger" asp-validation-for="CategoryId"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">Şəhər</label>
                                <select asp-for="CityId" id="" class="form-control cities">
                                    @foreach (var item in ViewBag.Cities.Datas)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }
                                </select>
                                <span class="text text-danger" asp-validation-for="CityId"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">İş stajı</label>
                                <input asp-for="Required_Experience" type="number" class="form-control" id="exampleInputEmail1" placeholder="Experience">
                                <span class="text text-danger" asp-validation-for="Required_Experience"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">İş saatı</label>
                                <select asp-for="Mode" class="form-control cities">
                                    @foreach (var mode in Enum.GetValues(typeof(JobMode)))
                                    {
                                        if ((int)mode != 0)
                                        {
                                            <option value="@mode">@mode</option>
                                        }
                                    }
                                </select>
                                <span asp-validation-for="Mode" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">Son tarix </label>
                                <input type="date"
                                       asp-for="EndDate"
                                       class="form-control inputs"
                                       placeholder="__/__/____" />
                                <span class="text text-danger" asp-validation-for="EndDate"></span>

                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">Əmək haqqı AZN</label>
                                <input type="number"
                                       max="12000"
                                       asp-for="Salary"
                                       class="form-control inputs"
                                       placeholder="Məs:1500" />
                                <span class="text text-danger" asp-validation-for="Salary"></span>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="vacans_inputs">
                                <label for="">Premium</label>
                                <div class="checkbox">
                                    <input asp-for="IsPremium" type="checkbox" class="form-check-input mt-0">
                                    <span>Premium</span>
                                    <span class="text text-danger" asp-validation-for="IsPremium"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-lg-2">
                    <h2 class="section_title">Conditions</h2>
                </div>
                <div class="col-lg-10">
                    <div class="adding user_add">
                        <div class="row">
                            <div class="col-lg-12">
                                <div method="post" class="form-group-2" id="form-container">
                                    <div style="width:100%">
                                        <input style="margin-top:5px;  width:100%;" class="form-control key " type="text" placeholder="Condition" asp-for="Conditions">
                                        <span asp-validation-for="Conditions"></span>
                                        <button style="font-size:20px;padding:5px 10px;margin-right:5px;margin-top:8px;" type="button" class="add-btn1 btn-primary">+</button>
                                        <button style="font-size:20px;padding:5px 10px;margin-right:5px;margin-top:8px;" type="button" class="remove-btn1 btn-primary">-</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="submit-button">
                <button class="btn btn-primary submit">Təsdiq et</button>
            </div>
        </form>
    </div>

    @section Scripts {
        <script src="~/HelloJobPanel/assets/js/postvacans.js"></script>

        <script>
            document.addEventListener('DOMContentLoaded', function () {
                const formContainer = document.getElementById('form-container');

                // Function to add new form group
                function addFormGroup() {
                    const formGroup1 = document.createElement('div');
                    formGroup1.classList.add('form-group-2');
                    formGroup1.innerHTML = `
                                                                  <div style="width:100%">
                                                    <input style="margin-top:5px;  width:100%;" class="form-control key " type="text" placeholder="Conditions" asp-for="Conditions">
                                                    <span asp-validation-for="Conditions"></span>
                                                    <button style="font-size:20px;padding:5px 10px;margin-right:5px;margin-top:8px;" type="button" class="add-btn1 btn-primary">+</button>
                                                    <button style="font-size:20px;padding:5px 10px;margin-right:5px;margin-top:8px;" type="button" class="remove-btn1 btn-primary">-</button>
                                                </div>
                                                            `;
                    formContainer.appendChild(formGroup1);

                    // Attach event listeners to the buttons in the new form group
                    const addBtns = document.querySelectorAll('.add-btn1');
                    const removeBtns = document.querySelectorAll('.remove-btn1');
                    addBtns.forEach(btn => btn.addEventListener('click', addFormGroup));
                    removeBtns.forEach(btn => btn.addEventListener('click', removeFormGroup));
                }
                // Function to remove form group
                function removeFormGroup(event) {
                    const formGroup = event.target.closest('.form-group-2');
                    if (formGroup !== null && formContainer.children.length > 1) {
                        formContainer.removeChild(formGroup);
                    }
                }

                // Attach event listener to the button in the initial form group
                const addBtn = document.querySelector('.add-btn1');
                addBtn.addEventListener('click', addFormGroup);
                const removeBtn = document.querySelector('.remove-btn1');
                removeBtn.addEventListener('click', removeFormGroup);
            });</script>
    }

HelloJob.App/Areas/User/Views/Vacancy/Index.cshtml
@model List<VacancyGetDto>
@inject ICategoryService categoryService;

@{
    List<CategoryGetDto> categories = (await categoryService.GetAllAsync()).Datas.ToList();
}
<div class="create_cv">
    <div class="title">
        <h1>Elanlarim</h1>
        <ul class="profile__add-cv__parts">
            <li class="active">
                <a href="#tab1" class="tab1 step_btn">Cv-lər(1)</a>
            </li>
            <li class="active d-none">
                <a href="#tab1" class="tab1 step_btn">Vakansiyalar(1)</a>
            </li>
        </ul>
    </div>
    <div class="inner_tab">
        <div class="container">
            <div class="row">
                @foreach (var item in Model)
                {
                <div class="col-lg-12 ">
                    <div class="user_block">
                        <a asp-area="" asp-controller="Vacancy" asp-action="Detail" asp-route-id="@item.Id" target="_blank">
                            <div class="header_user">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="user_img">
                                            <img src="~/assets/images/categories/@categories.FirstOrDefault(x=>x.Id==item.Category.ParentId).Image"
                                             alt="" />
                                    </div>
                                    <div class="d-flex justify-content-between w-100">
                                        <div class="user_desc">
                                            <h3 class="profession">
                                                @item.Position
                                            </h3>

                                            <p class="fullname">@item.Company.Name</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="user_options">
                                <div class="item">
                                    <div class="icon">
                                        <img src="https://www.hellojob.az/content/assets/images/resume/svg-icons/user-clock.svg"
                                             alt="" />
                                    </div>
                                    <div class="text">
                                        <h4>@item.Mode</h4>
                                        <p>İş rejimi</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="icon">
                                        <img src="https://www.hellojob.az/content/assets/images/resume/svg-icons/money.svg"
                                             alt="" />
                                    </div>
                                    <div class="text">
                                        <h4>@item.Salary</h4>
                                        <p>Minimum əmək haqqı AZN</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="icon">
                                        <img src="https://www.hellojob.az/content/assets/images/resume/svg-icons/briefcase.svg"
                                             alt="" />
                                    </div>
                                    <div class="text">
                                        <h4>@item.Required_Experience</h4>
                                        <p>İş staji</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <div class="user_buttons">
                                <a asp-controller="vacancy" asp-action="update" asp-route-id="@item.Id" class="edited btn">
                                <img src="https://www.hellojob.az/content/assets/images/profile/svg-icons/edit.svg"
                                     alt="" />
                                <span>Redaktə et</span>
                            </a>
                            <a class="deleted btn" asp-controller="vacancy" asp-action="remove" asp-route-id="@item.Id">
                                <img src="https://www.hellojob.az/content/assets/images/profile/svg-icons/delete.svg"
                                     alt="" />
                                <span>Sil</span>
                            </a>
                        </div>
                    </div>
                </div>
                    
                }
              
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/HelloJobPanel/assets/js/pageCv.js"></script>
   }