HelloJob.App/Areas/Admin/Controllers/CityController.cs
using HelloJob.Entities.DTOS;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace HelloJob.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class CityController : Controller
    {
        readonly ICityService _CityService;
        public CityController(ICityService CityService)
        {
            _CityService = CityService;
        }

        public async Task<IActionResult> Index(int page = 1,int pagesize=6)
        {

            return View(await _CityService.GetAllAsync(page,pagesize));
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CityPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var response = await _CityService.CreateAsync(dto);

            if (!response.Success)
            {
                ModelState.AddModelError("", response.Message);
                return View();
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            var res = await _CityService.GetAsync(id);
            return View(res.Data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, CityPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                var res = await _CityService.GetAsync(id);
                return View(res.Data);
            }
            var response = await _CityService.UpdateAsync(id, dto);

            if (!response.Success)
            {
                ModelState.AddModelError("", response.Message);
                var res = await _CityService.GetAsync(id);
                return View(res.Data);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Remove(int id)
        {
            var res = await _CityService.RemoveAsync(id);
            if (!res.Success)
            {
                ModelState.AddModelError("", res.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

HelloJob.App/Areas/Admin/Views/City/Create.cshtml
@model CityPostDto
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">City form</h4>
                        <p class="card-description">
                            City Create Form
                        </p>
                        <form enctype="multipart/form-data" method="post" class="forms-sample">
                            <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>

                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" type="text" class="form-control" id="exampleInputUsername1" placeholder="Name">
                                <span class="text text-danger" asp-validation-for="Name"></span>
                            </div>
                        
                         
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HelloJob.App/Areas/Admin/Views/City/Index.cshtml
@model PagginatedResponse<CityGetDto>


<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">City Table</h4>
                        <a asp-action ="create" class="badge badge-success">Create</a>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>

                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>CreateAt</th>
                                        <th>Operations</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Datas)
                                    {
                                        
                                    <tr>
                                            <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>
                                           @item.CreateAt
                                        </td>
                                        <td>
                                            <a onclick="return confirm('are you sure?')" asp-action="remove" asp-route-id="@item.Id" class="badge badge-danger">Remove</a> 
                                            <a asp-controller="City" asp-action="update" asp-route-id="@item.Id" class="badge badge-warning">Update</a>
                                        </td>

                                    </tr>
                                    }
                                
                                </tbody>
                            </table>


                           
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        <li class="page-item @(Model.PageNumber == 1 ? "disabled" : null)">
                                            <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageNumber - 1)" tabindex="-1">Previous</a>
                                        </li>
                                        @for (int i = 1; i <= Model.TotalPages; i++)
                                        {
                                            <li class="page-item @(i == Model.PageNumber ? "active" : null)">
                                                <a class="page-link" asp-action="Index" asp-route-page="@i">@i</a>
                                            </li>
                                        }
                                        <li class="page-item @(Model.TotalPages == Model.PageNumber ? "disabled" : null)">
                                            <a class="page-link" asp-action="Index" asp-route-page="@(Model.PageNumber + 1)">Next</a>
                                        </li>
                                    </ul>
                                </nav>
                        </div>
                    </div>
                </div>
            </div>
            </div>
    </div>
</div>

HelloJob.App/Areas/Admin/Views/City/Update.cshtml
@model CityGetDto
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title"> City form</h4>
                        <p class="card-description">
                            City Update Form
                        </p>
                        <form enctype="multipart/form-data" method="post" class="forms-sample">
                            <div class="alert alert-danger" asp-validation-summary="ModelOnly"></div>

                            <div class="form-group">
                                <label asp-for="Name">Name</label>
                                <input asp-for="Name" type="text" class="form-control" id="exampleInputUsername1" placeholder="Name">
                                <span class="text text-danger" asp-validation-for="Name"></span>
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>