HelloJob.App/Areas/Admin/Controllers/CompanyController.cs
using HelloJob.Core.Helper.MailHelper;
using HelloJob.Core.Utilities.Results.Concrete.ErrorResults;
using HelloJob.Core.Utilities.Results.Concrete.SuccessResults;
using HelloJob.Entities.DTOS;
using HelloJob.Entities.Enums;
using HelloJob.Entities.Models;
using HelloJob.Service.Services.Implementations;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace HelloJob.App.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class CompanyController : Controller
    {
        readonly ICompanyService _CompanyService;
        readonly IEmailHelper _emailHelper;
        public CompanyController(ICompanyService CompanyService, IEmailHelper emailHelper)
        {
            _CompanyService = CompanyService;
            _emailHelper = emailHelper;
        }

        public async Task<IActionResult> Index(string userid=null,int page = 1, int pagesize = 6)
        {
            return View(await _CompanyService.GetAllAsync(userid,true,page, pagesize));
        }

        public async Task<CompanyGetDto> GetCompanyById(int CompanyId)
        {
            var res = await _CompanyService.GetAsync(CompanyId);
            return res.Data ;
        }
        [HttpPost]
        public async Task<IActionResult> Accept(int id)
        {
            var result = await ProcessOrderStatus(id, "Muracietiniz qebul olundu");
            if (result.Success)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            else
            {
                return View(nameof(Index));
            }
        }
        [HttpPost]
        public async Task<IActionResult> Reject(int id)
        {
            var result = await ProcessOrderStatus(id, "Muracietiniz red edildi");

            if (result.Success)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            else
            {
                return View(nameof(Index));
            }
        }
        [HttpPost]
        public async Task<IActionResult> Pending(int id)
        {
            var result = await ProcessOrderStatus(id, "Muracietiniz gozlemededi");

            if (result.Success)
            {
                return Redirect(Request.Headers["Referer"].ToString());
            }
            else
            {
                return View(nameof(Index));
            }
        }
        private async Task<HelloJob.Core.Utilities.Results.Abstract.IResult> ProcessOrderStatus(int id, string emailSubject)
        {
            var Company = await GetCompanyById(id);

            if (Company == null)
            {
                return new ErrorResult("Company tapilmadi");
            }

            var userEmail = Company.AppUser.Email;

            var orderStatus = GetOrderStatusFromEmailSubject(emailSubject);

            if (orderStatus == Order.None)
            {
                var result = await _CompanyService.SetOrderStatus(id, orderStatus);

                if (result.Success)
                {
                    var notificationResult = await _emailHelper.SendNotificationEmailAsync(userEmail, "Pending", "netice gozlenilir");

                    if (notificationResult.Success)
                    {
                        return new SuccessResult("Pending bildirimi gönderildi");
                    }
                    else
                    {
                        return new ErrorResult("Pending bildirimi gönderilmedi");
                    }
                }
                else
                {
                    return new ErrorResult(result.Message);
                }
            }
            else
            {
                var result = await _CompanyService.SetOrderStatus(id, orderStatus);

                if (result.Success)
                {
                    var notificationResult = await _emailHelper.SendNotificationEmailAsync(userEmail, emailSubject, emailSubject);

                    if (notificationResult.Success)
                    {
                        return new SuccessResult(result.Message);
                    }
                    else
                    {
                        return new ErrorResult("Melumatlandirici e-postası gönderilmedi");
                    }
                }
                else
                {
                    return new ErrorResult(result.Message);
                }
            }
        }

        private Order GetOrderStatusFromEmailSubject(string emailSubject)
        {
            if (emailSubject == "Muracietiniz qebul olundu")
            {
                return Order.Accept;
            }
            else if (emailSubject == "Muracietiniz red edildi")
            {
                return Order.Reject;
            }
            else
            {
                return Order.None;
            }
        }


    }
}

HelloJob.App/Areas/User/Controllers/CompanyController.cs
using HelloJob.Entities.DTOS;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace HelloJob.App.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "Owner")]
    public class CompanyController : Controller
    {
        readonly ICompanyService _CompanyService;
  
        public CompanyController(ICompanyService CompanyService)
        {
            _CompanyService = CompanyService;
        }

        public async Task<IActionResult> Index(string userid,int page = 1,int pagesize=6)
        {
             userid = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.UserId = userid;
            var res = await _CompanyService.GetAllAsync(userid, false, page, pagesize);
            return View(res.Datas);
        }

        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Create()
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.UserId = userId;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Create(CompanyPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var response = await _CompanyService.CreateAsync(dto);


            if (!response.Success)
            {
                ModelState.AddModelError("", response.Message);
                return View();
            }

            return RedirectToAction(nameof(Index), new { userid = dto.AppUserId });
        }

        public async Task<IActionResult> Update(int id)
        {
            var userId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            ViewBag.UserId = userId;
            var res = await _CompanyService.GetAsync(id);
            return View(res.Data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner")]

        public async Task<IActionResult> Update(int id, CompanyPostDto dto)
        {
            if (!ModelState.IsValid)
            {
                var res = await _CompanyService.GetAsync(id);
                return View(res.Data);
            }
            var response = await _CompanyService.UpdateAsync(id, dto);

            if (!response.Success)
            {
                ModelState.AddModelError("", response.Message);
                var res = await _CompanyService.GetAsync(id);
                return View(res.Data);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Remove(int id)
        {
            var res = await _CompanyService.RemoveAsync(id);
            if (!res.Success)
            {
                ModelState.AddModelError("", res.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

HelloJob.App/Controllers/CompanyController.cs
using HelloJob.Data.DBContexts.SQLSERVER;
using HelloJob.Entities.DTOS;
using HelloJob.Entities.Models;
using HelloJob.Service.Services.Implementations;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HelloJob.App.Controllers
{

    public class CompanyController : Controller
    {
        readonly ICompanyService _CompanyService;

        public CompanyController(ICompanyService CompanyService)
        {
            _CompanyService = CompanyService;
        }


        public async Task<IActionResult> Index(List<CompanyGetDto>? Companys)
        {
            if (Companys.Count != 0)
            {
                return View(Companys);
            }
            else
            {
                var result = await _CompanyService.GetAllForCompanyPageInWebSiteAsync();
                return View(result.Data);
            }
        }
        public async Task<IActionResult> Detail(int id)
        {
            ViewBag.Companys = await _CompanyService.GetAllForCompanyPageInWebSiteAsync();
            var res = await _CompanyService.GetAsync(id);
            return View(res.Data);
        }

    }
}

HelloJob.App/Controllers/CourseController.cs
using HelloJob.Data.DBContexts.SQLSERVER;
using HelloJob.Entities.DTOS;
using HelloJob.Entities.Models;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HelloJob.App.Controllers
{
    public class CourseController : Controller
    {
        readonly ICourseService _CourseService;
        readonly ICategoryService _categoryService;
        readonly ITagService _tagService;

        public CourseController(ICourseService CourseService, ICategoryService categoryService, ITagService tagService)
        {
            _CourseService = CourseService;
            _categoryService = categoryService;
            _tagService = tagService;
        }

        public async Task<IActionResult> Index(List<CourseGetDto>? courses)
        {

            ViewBag.Categories = await _categoryService.GetAllAsync();
            if (courses.Count != 0)
            {

                return View(courses);
            }
            else
            {
                var result = await _CourseService.GetAllForCoursePageInWebSiteAsync();
                return View(result.Data);
            }
        }
        public async Task<IActionResult> Detail(int id)
        {
            var res = await _CourseService.GetAsync(id);
            return View(res.Data);
        }

        public async Task<IActionResult> SortCourses(int id, CourseFilterDto dto)
        {
            ViewBag.Dto=dto;
            var res = await _CourseService.SortCourses(id,dto);
            return PartialView("_CoursePartial", res.Data);
        }
        [HttpPost]
        public async Task<IActionResult> FilterCourses(CourseFilterDto dto)
        {
            var res = await _CourseService.FilterCourses(dto);
            return PartialView("_CoursePartial", res.Data);

        }



    }
}

HelloJob.App/Controllers/ResumeController.cs
using HelloJob.Core.Utilities.Results.Abstract;
using HelloJob.Core.Utilities.Results.Concrete;
using HelloJob.Data.DBContexts.SQLSERVER;
using HelloJob.Entities.DTOS;
using HelloJob.Entities.Models;
using HelloJob.Service.Services.Implementations;
using HelloJob.Service.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HelloJob.App.Controllers
{

    public class ResumeController : Controller
    {
        readonly IResumeService _ResumeService;
        readonly ICategoryService _categoryService;
        readonly IEducationService _educationService;
        readonly ILanguageService _languageService;
        readonly ILikedService _likeService;

        public ResumeController(IResumeService ResumeService, ICategoryService categoryService, IEducationService educationService, ILanguageService languageService, ILikedService likeService)
        {
            _ResumeService = ResumeService;
            _categoryService = categoryService;
            _educationService = educationService;
            _languageService = languageService;
            _likeService = likeService;
        }


        public async Task<IActionResult> Index(List<ResumeGetDto>? Resumes)
        {

            ViewBag.Categories = await _categoryService.GetAllAsync();
            ViewBag.Educations = await _educationService.GetAllAsync();
            ViewBag.Languages = await _languageService.GetAllAsync();
            if (Resumes.Count != 0)
            {
                return View(Resumes);
            }
            else
            {
                var result = await _ResumeService.GetAllForResumePageInWebSiteAsync();
                return View(result.Data);
            }
        }
        public async Task<IActionResult> Detail(int id)
        {
            ViewBag.Resumes = await _ResumeService.GetAllForResumePageInWebSiteAsync();
            var res = await _ResumeService.GetAsync(id);
            await _ResumeService.IncreaseCount(id);
            return View(res.Data);
        }

        public async Task<IActionResult> SortResumes(int id, ResumeFilterDto dto)
        {
            ViewBag.Dto=dto;
            var res = await _ResumeService.SortResumes(id,dto);
            return PartialView("_ResumePartial", res.Data);
        }
        [HttpPost]
        public async Task<IActionResult> FilterResumes(ResumeFilterDto dto)
        {
            var res = await _ResumeService.FilterResumes(dto);
           
            return PartialView("_ResumePartial", res.Data );
        }

        public async Task<IActionResult> LoadMore(int id,ResumeFilterDto dto,int pagenumber= 4, int pagesize = 3)
        {
            var res = await _ResumeService.LoadMoreResumesAsync(id,dto,pagenumber,pagesize);
            return PartialView("_ResumePartial", res.Data);
        }

        public async Task<IActionResult> Wishlist()
        {
            
                WishlistGetDto wishlist = await _likeService.GetWishList();
                if (wishlist is null)
                {
                    return Json("Wishlist is null");
                }
                return View(wishlist);
        }
        [HttpPost]
        public async Task<IActionResult> AddWishlist(int itemid, string itemtype)
        {
            await _likeService.AddToWishlist(itemid,itemtype);
            return Json(new
            {
                success = true,
            });

        }

    }
}

HelloJob.App/Views/Company/Detail.cshtml
  
 
@model CompanyGetDto

@inject IVacancyService vacancyService;

@{
    List<VacancyGetDto> vacancies = (await vacancyService.GetAllForVacancyPageInWebSiteAsync()).Data;
}
@inject ICategoryService categoryService;

@{
    List<CategoryGetDto> categories = (await categoryService.GetAllAsync()).Datas.ToList();
}

<!-- Main start  -->
<main class="main full" role="main">
    <div class="header-link">
        <div class="container">
            <ul>
                <li><a asp-controller="Home" asp-action="index">İş elanları</a></li>
                <li><a asp-controller="Resume" asp-action="index">CV - lər</a></li>
                <li><a asp-controller="Course" asp-action="index">Kurslar</a></li>
            </ul>
        </div>
    </div>
    <div class="breadcrumbs-block">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item color"><a href="#">Esas sehife</a></li>
                    <li class="breadcrumb-item color"><a href="#">Sirketler</a></li>
                    <li class="breadcrumb-item color" aria-current="page"><a href="#">@Model.Name</a></li>
                </ol>
            </nav>
        </div>
    </div>
    <section class="company">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="company__head">
                        <div class="company__head__top" style="background-image: url(https://www.hellojob.az/uploads/company/full/2023/11/27/645221892a0bf-8-o5Yd8tXg084UM.jpeg)">
                            <div class="company__head__logo">
                                <img loading="lazy" src="~/assets/images/companies/@Model.Image" alt="">
                            </div>
                        </div>
                        <div class="company__head__bottom">
                            <h2 class="company__head__name">@Model.Name</h2>
                            <nav class="company__head__nav">
                                <ul>
                                    <li><a href="#" class="tab__link active" data-tab="1">Vakansiyalar</a></li>
                                    <li><a href="#" class="tab__link " data-tab="2">Şirkət haqqında</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="tab__item active" data-tab="1">
                        <h2 class="section-title">Kapital Bank iş elanları</h2>
                        <div class="resumes my-0">
                            <div class="vacancies">
                                @foreach (var item in @vacancies.Where(x => x.Company.Id == Model.Id))
                                {
                                <a asp-controller="Home" asp-action="Detail" asp-route-id="@Model.Id" class="vacancies__item company-vacancy-item">
                                    <div class="vacancies__item__left">
                                        <div class="vacancies__icon">
                                                <img loading="lazy" src="~/assets/images/categories/@categories.FirstOrDefault(x=>x.Id==@item.Category.ParentId).Image" alt="Telesatış bölməsində kiçik mütəxəssis">
                                        </div>
                                        <div class="vacancies__desc">
                                            <h3>@item.Category.Name</h3>
                                            <p>@item.Company.Name</p>
                                                <span class="com_card_date">@item.EndDate.ToString("dd MMM yyyy")</span>
                                        </div>
                                    </div>
                                    <div class="vacancies__item__right">
                                        <span class="card_like " data-section="works" data-id="16429">
                                            <i id="unliked_ico" class="fa-regular fa-heart"></i>
                                            <i id="liked_ico" class="fa-solid fa-heart" style="
        display: none;color: #2196F3;top: 18px;
    "></i>
                                        </span>
                                    </div>
                                </a>
                                }
                            </div>
                        </div>
                        <h2 class="section-title pt-4">
                            Vaxtı bitmiş vakansiyalar
                        </h2>
                        <div class="resumes my-0">
                            <div class="vacancies">
                                @foreach (var item in vacancies.Where(x => x.EndDate <= DateTime.Now && x.Company.Id == Model.Id))
                                {
                                <a asp-controller="Home" asp-action="Detail" asp-route-id="@item.Id" class="vacancies__item company-vacancy-item">
                                    <div class="vacancies__item__left">
                                        <div class="vacancies__icon">
                                                <img loading="lazy" src="~/assets/images/categories/@categories.FirstOrDefault(x=>x.Id==@item.Category.ParentId).Image" alt="Şəmkir filialı üzrə Mikrokreditlər bölməsinin kiçik mütəxəssisi">
                                        </div>
                                        <div class="vacancies__desc">
                                            <h3>@item.Category.Name</h3>
                                                <p>@item.Company.Name</p>
                                                <span class="com_card_date">@item.EndDate.ToString("dd MMM yyyy")</span>
                                        </div>
                                    </div>
                                    <div class="vacancies__item__right">
                                        <span class="card_like" data-section="works" data-id="16106">
                                            <i id="unliked_ico" class="fa-regular fa-heart"></i>
                                            <i id="liked_ico" class="fa-solid fa-heart" style="
        display: none; color: #2196F3;top: 18px;
    "></i>
                                        </span>
                                    </div>
                                </a>
                                    
                                }
                            </div>
                        </div>
                </div>
                    <div class="tab__item " data-tab="2">
                        <h2 class="section-title">şirkət haqqında</h2>
                        <div class="content">
                            <p>
                                 @Model.About
                            </p>
                        </div>
                    </div>
            </div>
                <div class="col-lg-4">
                    <div class="resume__block--contact inner_fixed_bottom">
                        <div class="contact">
                            <div class="contact__head">
                                <h4>Kontakt məlumatları</h4>
                                <a href="#" class="company__contact__icon contact-btn mr-0 d-md-none">
                                    <img loading="lazy" src="https://www.hellojob.az/content/assets/images/resume/svg-icons/arrow-bottom.svg" alt="">
                                </a>
                            </div>
                            <div class="contact__body">
                                <div class="contact__top">
                                    <h4>Kontakt məlumatları</h4>
                                    <div class="resume__item">
                                        <div class="resume__icon">
                                            <img loading="lazy" src="https://www.hellojob.az/content/assets/images/resume/svg-icons/mail.svg" alt="">
                                        </div>
                                        <div class="resume__item__text">
                                            <h4 class="hidd_email">E-poçtu göstər</h4>
                                            <h4 class="hidd_email d-none"></h4>
                                            <p>@Model.Email</p>
                                        </div>
                                        <button class="resume__icon hidden_toggle hidden_toggle-email mr-0">
                                        </button>
                                    </div>
                                    <div class="resume__item mb-0">
                                        <div class="resume__icon">
                                            <img loading="lazy" src="https://www.hellojob.az/content/assets/images/company/globe.svg" alt="">
                                        </div>
                                        <div class="resume__item__text">
                                            <h4><a href="@Model.WebsiteUrlLink" target="_blank">https://kapitalbank.az</a></h4>
                                            <p>Veb səhifəsi</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        </div>
        <div class="blog_inner_tags"></div>
    </section>
    <script type="text/javascript">
        $('.contact-btn').click(function (e) {
            e.preventDefault();
            $(this).toggleClass('open')
            $('.contact__body').slideToggle();
        })
    </script>
</main>
<!-- Main end  -->
@section Scripts {
    <script src="~/assets/js/company-detail.js"></script>
   }

HelloJob.App/Views/Company/Index.cshtml
@model List<CompanyGetDto>
@inject IVacancyService vacancyService;

@{
    List<VacancyGetDto> vacancies = (await vacancyService.GetAllForVacancyPageInWebSiteAsync()).Data;
}


<main class="main full" role="main">
    <div class="col-md-12 breadc  new_breadcrumb">
        <div class="container two_side_breadc">
            <h3>Şirkətlər</h3>
            <ul>
                <li>
                    <a asp-action="index" asp-controller="Home">Əsas səhifə </a>
                </li>
                <li>
                    <a asp-controller="company" asp-action="Index">Şirkətlər</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
        <div class="col-md-12 companies_section p-0">
            <div class="row">
                @foreach (var item in Model)
                {
                <div class="company_card col-md-4 col-lg-3">
                    <div class="company_box">
                        <a asp-controller="Company" asp-action="detail" asp-route-id="@item.Id" class="full">
                            <div class="n_company_images">
                                <img loading="lazy" src="~/assets/images/companies/@item.Image" alt="ABB ASC">
                            </div>
                            <p>@item.Name</p>
                            <span>Vakansiya sayı<span>@vacancies.Where(x=>x.Company.Id==item.Id).Count()</span> </span>
                        </a>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</main>
@section Scripts {
    <script src="~/assets/js/company.js"></script>
   }